export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const GET_SERVICE_REQUEST = "GET_SERVICE_REQUEST";
export const GET_SERVICE_FAILURE = "GET_SERVICE_FAILURE";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";